# SPDX-License-Identifier: LGPL-3.0-or-later
# Minimal cloud-netconfig configuration

# Basic logging
logging:
  level: info
  format: text

# Server defaults
server:
  listen:
    address: 127.0.0.1
    port: 5209

# Auto-detect and use defaults for everything else
